<?php
/**
 * @file
 * Code for the OpenSourcery Slideshow feature.
 */

include_once('os_slideshow.features.inc');

/**
 * Implements hook_bean_types_api_info().
 */
function os_slideshow_bean_types_api_info() {
  return array(
    'api' => 1,
  );
}

/**
 * Implements hook_bean_types().
 */
function os_slideshow_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'os_slideshow') .  '/plugins/bean';

  $plugins['slideshow'] = array(
    'label' => t('Slideshow'),
    'handler' => array(
      'class' => 'slideshow_bean',
      'parent' => 'bean',
    ),
    'path' => $plugin_path,
    'file' => 'slideshow.inc',
  );
  return $plugins;
}
