<?php
/**
 * @file
 * Code for the OpenSourcery Slideshow feature.
 */

include_once('os_slideshow.features.inc');

/**
 * Implements hook_form_FORM_ID_alter().
 */
function os_slideshow_form_bean_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#bundle'] === 'slideshow') {
    $form['#attached']['css'][] = drupal_get_path('module', 'os_slideshow') . '/os_slideshow.css';
  }
}

/**
 * Implements hook_bean_types_api_info().
 */
function os_slideshow_bean_types_api_info() {
  return array(
    'api' => 1,
  );
}

/**
 * Implements hook_bean_types().
 */
function os_slideshow_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'os_slideshow') .  '/plugins/bean';

  $plugins['slideshow'] = array(
    'label' => t('Slideshow'),
    'handler' => array(
      'class' => 'slideshow_bean',
      'parent' => 'bean',
    ),
    'path' => $plugin_path,
    'file' => 'slideshow.inc',
  );
  return $plugins;
}

/**
 * Creates a new slide and adds it to the given slideshow bean.
 */
function os_slideshow_add_slide($bean, $image_path, $headline, $teaser, $link_title, $link_path) {
  // Create a new slide field_collection entity
  $slide = entity_create('field_collection_item', array('field_name' => 'field_slideshow_slides'));
  $slide->field_slide_headline['und'][0]['value'] = $headline;
  $slide->field_slide_teaser['und'][0]['value'] = $teaser;
  $slide->field_slide_teaser['und'][0]['format'] = 'full_html';
  $slide->field_slide_link['und'][0]['title'] = $link_title;
  $slide->field_slide_link['und'][0]['url'] = $link_path;
  $slide->setHostEntity('bean', $bean);

  $file = (object) array(
    'uid' => 1,
    'uri' => $image_path,
    'filemime' => file_get_mimetype($image_path),
    'status' => 1,
  );
  $file = file_copy($file, 'public://');
  $slide->field_slide_image['und'][0] = (array)$file;
  $slide->field_slide_image['und'][0]['display'] = TRUE;
  $slide->save();
}
